### ISSUE TITLE
NFS partition resize and routing issues

### ISSUE THREAD

**Issue by Dr-Drive** [twobitcircus/rpi-build-and-boot#14]
Hello there!
I originally installed the repository from Thomas Van Ta, and after some efforts, this rpi development scheme works like a charm on Yosemite and Wheezy Raspbian 2015-02-16
I apologize in advance for the noob questions, but I just recently got started with the rpi after some years of linux experience. So here are the two questions:
1) How and where do I configure routing so that the RPI sees the rest of the web, in addition to the http proxy on the vagrant machine? I mean apt-get works great but I cannot even see my local sub-networks from the rpis (my local subnetwork can see the rpis though.
2) The wheezy image is only 3.2 GB, I would like to expand it but I really do not know how to go about it. Could you please provide advice on how to resize the shared root nfs partition mounted on the vagrant vm? 
3) Also, if it is not too much to ask, please provide advice on how to resize the vagrant vm partition.

**Comment by egradman** [comment]
Glad it's working out for you!

1. If you'd like the Raspberry Pi to have full access to the internet (rather than just proxy access) you have to install IP masquerading on the Linux box.  I haven't tested these instructions, but something like this http://linux.about.com/od/ubusrv_doc/a/ubusg18t03.htm is an outline to accomplish what you want.
2. I don't know that it's possible to do this without creating a new image.  The process would be:
    - dd a regular Raspbian image to a card of the desired size, and boot it up in a pi.
    - When it asks you to expand the filesystem, allow it to do so.
    - Shut down the pi, put the SD card in your computer, and dd the card to a new image file on disk.
3. Resizing the partition depends on what virtual machine environment you're using.  You're probably using virtualbox. I don't use virtualbox, I use Parallels.  Follow the virtualbox instructions.

**Comment by Dr-Drive** [comment]
Thanks! That makes sense =)
Great work by the way...

**Comment by Dr-Drive** [comment]
I had originally done 
qemu-img resize 2014-01-07-wheezy-raspbian.img +8GB
To increase the image 8GB, it looks like 8GB larger, but the system is not registering the size change.
I tried the fdisk method on https://raspberry-hosting.com/en/faq/how-expand-arch-linux-root-partition
but it does not seem to be able to see the end block beyond the original 3GB

Any thoughts on what would happen if I run the raspi-config on the NFS mounted rpi?
Would it expand on the SD card or on the NFS drive?
